# blacklist
branches:
  except:
    - master
		
# whitelist
branches:
  only:
    - feature/laco/TestStream
    - devel
   
language: java
jdk:
- oraclejdk8
env:
- BUILD_TYPE=dev
before_install:
- ./scripts/before-install.sh
install:
  - mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
script:
 - mvn test jacoco:report coveralls:report -Dgpg.skip -Dmaven.javadoc.skip=true -B
