server:
  port: 8888
 
spring:
  cloud:
    config:
      server:
        git:
          uri: ${user.dir}/../../strg-service-properties
          #uri: ${GIT_URI}
          #username: ${GIT_USR}
          #password: ${GIT_PWD}
          